### ISSUE TITLE
只是想轮播图片, 就像是放PPT一样

### ISSUE THREAD

**Issue by crazypeace** [bytelang/kplayer-go#121]
只是想轮播图片, 就像是放PPT一样
资源列表里面只有图片可以吗?
怎么设置每张图片的播放时长?

**Comment by crazypeace** [comment]
配置文件这样
```
version: 2.0.0
resource:
  lists:
    - unique: qfl-res
      seek: 10
      end: 20
      groups:
        - path: /home/user/pic/1.png
          media_type: video
          persistent_loop: true
        - path: /home/user/music/1.mp3
          media_type: audio
    - unique: qfl-res
      seek: 10
      end: 20
      groups:
        - path: /home/user/pic/2.png
          media_type: video
          persistent_loop: true
        - path: /home/user/music/2.mp3
          media_type: audio
    - unique: qfl-res
      seek: 10
      end: 20
      groups:
        - path: /home/user/pic/3.png
          media_type: video
          persistent_loop: true
        - path: /home/user/music/3.mp3
          media_type: audio
    - unique: qfl-res
      seek: 10
      end: 20
      groups:
        - path: /home/user/pic/4.png
          media_type: video
          persistent_loop: true
        - path: /home/user/music/4.mp3
          media_type: audio
output:
  lists:
    - path: rtmp://a.rtmp.youtube.com/live2/c1cz-4y7x-85wx-jpde-9kaa
play:
  play_model: loop
  cache_on: true
  fill_strategy: ratio
  skip_invalid_resource: true
  encode:
    video_width: 1920
    video_height: 1080
```

运行报错
```
root@fuckgfw:~/kplayer# ./kplayer play start -d

kplayer for golang v0.5.8 Copyright(c) 2019-2023 the ByteLang Studio (https://kplayer.bytelang.cn)
  libkplayer version: v1.5.4-1-ge0cab16 plugin version: 1.5.1 license version: v1 
  toolchains GNU(10.3.1) C++ Standard 17 on Linux-x86_64-6.0.2-arch1-1
  build with build-chains cmake(3.21.3) type with Release
  Hope you have a good experience.
-------------------------------------------------------------------------------------------------------------------
FATA[2023-07-23 15:59:00] start point invalid. cannot great than total resource 

```
