### ISSUE TITLE
yaml配置文件不生效

### ISSUE THREAD

**Issue by sanwecn** [bytelang/kplayer-go#74]
```
plugin:
  lists:
    - path: show-progress
      unique: show-progress
      params:
        fontsize: '14'
        x: '10'
        y: '10'
```
这段配置转换成json可以生效，yaml格式的配置文件不生效。
